version: '3.8'

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    command: flask run --host=0.0.0.0
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    env_file:
      - ./config/.env
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mongo:4.2.6-bionic
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - ./config/.env
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local