version: '3.8'

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    command: flask run --host=0.0.0.0
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    env_file:
      - ./config/.env